spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///parking?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8086
