spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  datasource:
    username: root
    password: Lianfukeji666
    url: jdbc:mysql://rm-m5e7523t24326u9638o.mysql.rds.aliyuncs.com/parking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lianfu.pojo
server:
  port: 8088
  servlet:
    context-path: /parking
rain:
  appid: ruibangjiajv

